version: '3'
services:
  nest:
    build: .
    container_name: nest
    volumes:
      - ./src:/app/src
      - .env:/app/.env

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-Nginx
    container_name: nest-nginx
    depends_on:
      - nest
    environment:
      - NGINX_SERVER_NAME=localhost
      - NEST_HOST=nest
      - NEST_PORT=8001
      - NGINX_MAX_BODY=100M
    ports:
      - 80:80